Role based protection implementation. Closes #113
AcademicHubOrg/AcademicHub pull request #133
Opened 2023-12-03 17:50 UTC by roflmyrlok

This branch covers issue #113 and adds role based access to endpoints.

2023-12-05 09:04 UTC, YaroslavKSE approved these changes
High quality code by Andrew Tate. Approved!

2023-12-11 21:33 UTC, Bardin08 requested changes

2023-12-11 21:33 UTC, Bardin08 commented on Identity/Identity.Core/UsersService.cs
> +		var tmp = await _repository.FindByEmailAsync(email);
What's with naming?!

2023-12-11 21:33 UTC, Bardin08 commented on Identity/Identity.Core/UsersService.cs
> +		return (true, true);
That's horrible! Better return `bool?`

2023-12-11 21:33 UTC, Bardin08 commented on Identity/Identity.Data/Migrations/20231203171615_AuthChecks.cs
> +        }
Why it's empty and here?

2023-12-11 21:33 UTC, Bardin08 commented on Identity/Identity/EndpointHandlers.cs
> +    public static async Task<object> MakeAdmin([FromServices] UsersService service, HttpContext httpContext, string emailToMakeAdmin, string password)
`emailToPromote___` sound better for me

2023-12-11 21:33 UTC, Bardin08 commented on Identity/Identity/EndpointHandlers.cs
> +    public static async Task<object> MakeAdmin([FromServices] UsersService service, HttpContext httpContext, string emailToMakeAdmin, string password)
Also makes sense to wrap this to some kind of request model

2023-12-13 14:42 UTC, closed without merging