Fix: use environment variables to hide secret and client id
AcademicHubOrg/AcademicHub pull request #81
Opened 2023-11-20 16:12 UTC by YaroslavKSE

@podkolzzzin I have use environment variables to hide secret and client id. However, I can't configure secrets as I haven't got permissions. You can add them by yourself or I can use your pc to add them

2023-11-20 17:55 UTC, podkolzzzin commented
I have transferred project to the organization and granted you admin access.
Hope it works.

2023-11-20 19:13 UTC, YaroslavKSE commented
> I have transferred project to the organization and granted you admin access. Hope it works.

Thanks, I can add secretes now

2023-11-22 15:10 UTC, Bardin08 requested changes
@YaroslavKSE PR looks good to me, but:
- Remove Rider's cache from it
- Please confirm that:
	- Google OAuth secrets rotated
	- Google OAuth secrets added to the repos SECRETS (not variables)

When done please ping me and I will approve this PR

2023-11-22 15:10 UTC, Bardin08 commented on Identity/.idea/config/applicationhost.config
> +<?xml version="1.0" encoding="utf-8"?>
Please remove this, as it's an IDE-related file. It's some Rider's cache

2023-11-22 23:21 UTC, Bardin08 commented
@YaroslavKSE I closed this PR because it didn't resolve security issues, as variables are still in the codebase. Instead, please check the approach defined in the #90. There is used a well-known feature called user secrets.

### Useful links:
- https://blog.jetbrains.com/dotnet/2023/01/17/securing-sensitive-information-with-net-user-secrets/

2023-11-22 23:21 UTC, closed without merging