Cover the code CourseTemplate with UnitTests
AcademicHubOrg/AcademicHub pull request #97
Opened 2023-11-23 18:08 UTC by kmirik999

2023-11-23 19:10 UTC, Bardin08 requested changes

2023-11-23 19:10 UTC, Bardin08 commented on CourseTemplate/CourseTemplate.UnitTests/UnitTest1.cs
> +			var service = new CourseTemplateService(mockRepository.Object);
Code duplication

2023-11-23 19:10 UTC, Bardin08 commented on CourseTemplate/CourseTemplate.UnitTests/UnitTest1.cs
> +			var service = new CourseTemplateService(mockRepository.Object);
Code duplication

2023-11-23 19:11 UTC, Bardin08 commented
Also, please rename tests file to something more manful

2023-11-24 21:22 UTC, YaroslavKSE approved these changes
LGTM. 100% of coverege of Core Layer - thats perfect!

2023-11-25 10:09 UTC, YaroslavKSE approved these changes

2023-11-25 14:17 UTC, roflmyrlok approved these changes
tests are good, approve!

2023-11-25 14:19 UTC, YaroslavKSE approved these changes

2023-11-26 14:57 UTC, YaroslavKSE approved these changes

2023-11-26 14:59 UTC, merged